version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "monthly"
  
