name: Dependency Review

on: 
  workflow_call:
    inputs:
      manifests:
        description: A JSON array of Java environments
        type: string
        required: true
jobs:
  dependency_analysis:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(inputs.manifests) }}
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        if: ${{ matrix.java-version != '' && matrix.java-distribution != '' }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }} 
          distribution: ${{ matrix.java-distribution}} 
      
      
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
        with:
          directory: ${{ matrix.directory }}
          correlator: ${{ github.job }}-${{ matrix.directory }}
      - name: Dependency validation
        if: ${{ github.event_name == 'pull_request' }}
        id: dependency_validation
        uses: actions/dependency-review-action@v2
        continue-on-error: true
        with:
          fail-on-scopes: "runtime, development, unknown"
      - name: Publish status to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: octodemo/github-status-action@v2
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: ${{ steps.dependency_validation.outcome }}
          context: Dependency scanning results / Dependency Review
          description: "${{ steps.dependency_validation.outcome }} (see details for more information)"
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
